FROM python:3.10.13-slim

WORKDIR /app
RUN apt-get -y update && apt-get -y upgrade
RUN RUN apt-get -y install git build-essential
RUN git clone https://github.com/anshjoseph/StyleTTS_Server.git
RUN cp -a StyleTTS_Server/. .
RUN pip install -r requirements.txt 
EXPOSE 8700
CMD ["python3","main.py"]